version: '2.4'

services:

  mauticdb:
    image: percona/percona-server:8.0
    container_name: mauticdb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic-net

  # To test locally, temporarily remove the `alb-safe-index.php` modification
  # (either in that file or by commenting the relevant bit of `entrypoint.sh`
  # before the build). And comment the S3 custom bits of `secrets_entrypoint.sh`
  # or stop the image using that entrypoint.
  mautic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mautic
    links:
      - mauticdb
    depends_on:
      - mauticdb
    ports:
      - '8080:80'
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_URL=http://localhost:8080
    networks:
      - mautic-net

volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  mautic-net:
    driver: bridge
