version: '2.4'

services:

  mauticdb:
    image: percona/percona-server:8.0
    container_name: mauticdb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic-net

  mautic:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: apache2-foreground
    container_name: mautic
    links:
      - mauticdb
    depends_on:
      - mauticdb
    ports:
      - '8080:80'
    environment:
      - MAUTIC_ENV=dev
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_URL=http://localhost:8080
    networks:
      - mautic-net

volumes:
  mysql_data:
    driver: local
networks:
  mautic-net:
    driver: bridge
