<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.h.1W_d_' shared service.

return $this->privates['.service_locator.h.1W_d_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'event' => ['privates', '.errored..service_locator.h.1W_d_.Symfony\\Component\\HttpKernel\\Event\\FilterControllerEvent', NULL, 'Cannot autowire service ".service_locator.h.1W_d_": it references class "Symfony\\Component\\HttpKernel\\Event\\FilterControllerEvent" but no such service exists.'],
], [
    'event' => 'Symfony\\Component\\HttpKernel\\Event\\FilterControllerEvent',
]);
