<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DZfjq96' shared service.

return $this->privates['.service_locator.DZfjq96'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
], [
    'dispatcher' => '?',
]);
