<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Wiujwnm' shared service.

return $this->privates['.service_locator.Wiujwnm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'e' => ['privates', '.errored..service_locator.Wiujwnm.Exception', NULL, 'Cannot autowire service ".service_locator.Wiujwnm": it references class "Exception" but no such service exists.'],
], [
    'e' => 'Exception',
]);
