<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.emwFe8t' shared service.

return $this->privates['.service_locator.emwFe8t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.emwFe8t.Mautic\\UserBundle\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.emwFe8t": it references class "Mautic\\UserBundle\\Entity\\User" but no such service exists.'],
], [
    'user' => 'Mautic\\UserBundle\\Entity\\User',
]);
