<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.r0srwDw' shared service.

return $this->privates['.service_locator.r0srwDw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'factory' => ['services', 'mautic.factory', 'getMautic_FactoryService', false],
], [
    'factory' => '?',
]);
