<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5_09ROW' shared service.

return $this->privates['.service_locator.5_09ROW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'flashBag' => ['services', 'mautic.core.service.flashbag', 'getMautic_Core_Service_FlashbagService', false],
], [
    'flashBag' => '?',
]);
