<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.emwFe8t.Mautic\UserBundle\Entity\User' shared service.

$this->throw('Cannot autowire service ".service_locator.emwFe8t": it references class "Mautic\\UserBundle\\Entity\\User" but no such service exists.');
