<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQRfTRNs\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQRfTRNs/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQRfTRNs.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQRfTRNs\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQRfTRNs\appAppKernelProdContainer([
    'container.build_hash' => 'QRfTRNs',
    'container.build_id' => '0e2277e1',
    'container.build_time' => 1691010813,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQRfTRNs');
